### PR TITLE
A few Refactorings

### PR DESCRIPTION
**Pull request by zhiburt**
Hi @patrickelectric 

It makes a few refactorings; mainly `clippy` warnings

### CODE REVIEW

**Comment by zhiburt** [comment]
It must make no logic changes.
I did not test it though...

A few thoughts.

1. Probably it's better to keep artifacts in target directory.
2. It could check the artifacts before downloading to not waste build time and being able to build it offline

**Review by patrickelectric — APPROVED** [review]
Looks good!

**Comment by patrickelectric** [comment]
@zhiburt can you rebase ?

**Comment by zhiburt** [comment]
Not sure if it was correctly merged (there was some strange things with git regarding branch name)

**Comment by patrickelectric** [comment]
@zhiburt please avoid merge, use rebase.

**Pull request closed without merging**
